apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: ./
    targetRevision: main
    repoURL: https://github.com/marcolam-sandboxvr/gitops-demo.git
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    retry: {}
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
